# Generated by Django 5.2.7 on 2025-10-29 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_tags', to='Notes.note')),
            ],
        ),
    ]
