# Generated by Django 5.2.7 on 2025-11-04 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutPlan', '0002_exercises_alter_exerciselog_exercise_delete_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('rest_time', models.IntegerField(help_text='Rest time in seconds')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='WorkoutPlan.workoutplan')),
            ],
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutPlan.exercise'),
        ),
        migrations.DeleteModel(
            name='Exercises',
        ),
    ]
