# Generated by Django 5.2.7 on 2025-11-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutPlan', '0003_exercise_alter_exerciselog_exercise_delete_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='Workout_list',
            field=models.CharField(choices=[('Pullup', 'Pullup'), ('Pushup', 'Pushup'), ('Plank', 'Plank'), ('Squat', 'Squat'), ('Lunges', 'Lunges'), ('Jumping Jacks', 'Jumping Jacks'), ('high knees', 'high knees'), ('Burpees', 'Burpees'), ('Mountain Climbers', 'Mountain Climbers'), ('Sit-ups', 'Sit-ups'), ('Leg Raises', 'Leg Raises'), ('Bicycle Crunches', 'Bicycle Crunches'), ('Russian Twists', 'Russian Twists'), ('Superman Exercise', 'Superman Exercise'), ('Tricep Dips', 'Tricep Dips'), ('Wall Sit', 'Wall Sit'), ('Calf Raises', 'Calf Raises'), ('Glute Bridges', 'Glute Bridges'), ('Donkey Kicks', 'Donkey Kicks'), ('Fire Hydrants', 'Fire Hydrants')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='calories_burned',
            field=models.IntegerField(null=True),
        ),
    ]
