# Generated by Django 5.2.7 on 2025-11-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutPlan', '0004_exercise_workout_list_exercise_calories_burned'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='WorkoutPlan',
            field=models.ManyToManyField(blank=True, related_name='workout_plans', to='WorkoutPlan.exercise'),
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='workout_plan',
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout_plan',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='WorkoutPlan.workoutplan'),
        ),
    ]
