# Generated by Django 5.2.7 on 2025-10-29 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0002_workoutlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutfeedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workoutlist',
            name='user',
        ),
    ]
