# Generated by Django 5.2.7 on 2025-10-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0003_remove_workoutfeedback_user_remove_workoutlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='Workout_list',
            field=models.CharField(choices=[('Pullup', 'Plank'), ('Pushup', 'Situp')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Workoutlist',
        ),
    ]
