# Generated by Django 5.2.7 on 2025-10-29 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_deleteuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivitylog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='deleteUser',
        ),
        migrations.DeleteModel(
            name='UserActivityLog',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
