# Generated by Django 5.2.7 on 2025-11-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deleteUser',
        ),
    ]
