# Generated by Django 5.2.7 on 2025-10-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AddField(
            model_name='tag',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
